---
# Changes here will be overwritten by Copier
_commit: v2.45.0
_src_path: gh:remerge/template
project_id: workflows
project_license: private
project_name: GitHub Actions Workflows
project_owner: core
project_type: default
use_ansible: false
use_consul: false
use_golang: false
use_nodejs: false
use_nomad: false
use_python: false
use_ruby: false
use_terraform: false
