---
default_stages:
  - pre-commit

default_install_hook_types:
  - commit-msg
  - pre-commit
  - prepare-commit-msg

repos:
  # https://github.com/pre-commit/pre-commit-hooks/tags
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v6.0.0"
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: forbid-submodules
      - id: trailing-whitespace
        exclude: "^.gitignore$"

  # https://github.com/prettier/prettier/tags
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: prettier --write --list-different --ignore-unknown
        language: node
        types: [text]
        exclude: "^project/"
        additional_dependencies:
          - "prettier@3.6.2"

  # https://github.com/igorshubovych/markdownlint-cli/tags
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: "v0.45.0"
    hooks:
      - id: markdownlint-fix
        name: markdownlint

  # https://github.com/adrienverge/yamllint/tags
  - repo: https://github.com/adrienverge/yamllint
    rev: "v1.37.1"
    hooks:
      - id: yamllint
        entry: yamllint --strict

  # https://github.com/pecigonzalo/pre-commit-shfmt/tags
  - repo: https://github.com/pecigonzalo/pre-commit-shfmt
    rev: "v2.2.0"
    hooks:
      - id: shell-fmt-go

  # https://github.com/koalaman/shellcheck-precommit/tags
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: "v0.11.0"
    hooks:
      - id: shellcheck
        name: shellcheck

  # https://github.com/rhysd/actionlint/tags
  - repo: https://github.com/rhysd/actionlint
    rev: "v1.7.7"
    hooks:
      - id: actionlint-docker
        name: actionlint

  # https://github.com/bridgecrewio/checkov/tags
  - repo: https://github.com/bridgecrewio/checkov
    rev: "3.2.461"
    hooks:
      - id: checkov
        name: checkov
        args: [--config-file=.checkov.yml, --skip-path=vendor]

  # https://github.com/jorisroovers/gitlint/tags
  - repo: https://github.com/jorisroovers/gitlint
    rev: "v0.19.1"
    hooks:
      - id: gitlint

  # https://github.com/get-woke/woke/tags
  - repo: https://github.com/get-woke/woke
    rev: "v0.19.0"
    hooks:
      - id: woke-from-source
        args: [--config=.woke.yaml]
