---
extends: default

ignore: |
  .copier-answers.yml
  .cache/
  .tox/

rules:
  comments:
    min-spaces-from-content: 1
  comments-indentation: disable
  line-length: disable
  truthy:
    allowed-values: ["true", "false"]
    check-keys: false
  braces:
    max-spaces-inside: 1
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true
