---
name: GCP deploy static website

on:
  workflow_call:
    inputs:
      bucket:
        type: string
        required: true
        description: "GCS bucket to deploy to without gs:// prefix"

      upload_folder:
        type: string
        required: false
        default: build
        description: "Folder with built content"

      package_manager:
        type: string
        required: false
        default: yarn
        description: "Node Package manager i.e yarn, npm"

      node_version_file:
        type: string
        required: false
        default: .node-version
        description: "Node version File"

      install_command:
        type: string
        required: false
        default: yarn install
        description: "Install command"

      build_command:
        type: string
        required: false
        default: yarn run build
        description: "Build command"

      working_directory:
        type: string
        required: false
        default: .
        description: "Path to run build"

      env_file:
        type: string
        required: false
        default: .env
        description: "build env file"
    secrets:
      rollbar_access_token:
        required: true

jobs:
  deploy:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    env:
      GITHUB_REF: ${{ github.ref }}
      ROLLBAR_ACCESS_TOKEN: ${{ secrets.rollbar_access_token}}
    steps:
      - id: "checkout"
        uses: "actions/checkout@v4"

      - uses: actions/setup-node@v4
        with:
          cache: ${{ inputs.package_manager }}
          cache-dependency-path: ${{ inputs.working_directory }}
          node-version-file: ${{ inputs.node_version_file }}

      - name: Install dependencies
        run: |
          set -ex
          ${{ inputs.install_command }}
        working-directory: ${{ inputs.working_directory }}

      - name: Build application
        run: |
          set -aex
          [ -f ${{ inputs.env_file }} ] && source ${{ inputs.env_file }}
          set +a
          ${{ inputs.build_command }};
        working-directory: ${{ inputs.working_directory }}

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: ${{ vars.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
          # project_id: ${{ vars.CLOUDSDK_CORE_PROJECT }}
          service_account: ${{ vars.GOOGLE_DEFAULT_SERVICE_ACCOUNT }}

      - id: "upload-folder"
        uses: "google-github-actions/upload-cloud-storage@v2"
        with:
          path: ${{ format('{0}/{1}',inputs.working_directory,inputs.upload_folder) }}
          destination: ${{ inputs.bucket }}
          parent: false

      - name: Notify app deploy to Rollbar
        uses: rollbar/github-deploy-action@2.1.1
        id: rollbar_deploy_ui
        with:
          environment: "production"
          version: ${{ github.sha }}
        env:
          ROLLBAR_ACCESS_TOKEN: ${{ secrets.rollbar_access_token }}
          ROLLBAR_USERNAME: ${{ github.actor }}
