---
name: GCP deploy static website

on:
  workflow_call:
    inputs:
      bucket:
        type: string
        required: true
        description: "GCS bucket to deploy to without gs:// prefix"

      build_folder:
        type: string
        required: false
        default: build
        description: "Folder with built content"

      package_manager:
        type: string
        required: false
        default: yarn
        description: "Node Package manager i.e yarn, npm"

      node_version_file:
        type: string
        required: false
        default: .node-version
        description: "Node version File"

      build_command:
        type: string
        required: false
        default: yarn install
        description: "Build command"

      build_path:
        type: string
        required: false
        default: .
        description: "Path to run build"

      env_file:
        type: string
        required: false
        default: .env
        description: "build env file"

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
    - id: 'checkout'
      uses: 'actions/checkout@v4'

    - uses: actions/setup-node@v4
      with:
        cache: ${{ inputs.package_manager }}
        cache-dependency-path: ${{ inputs.build_path }}
        node-version-file: ${{ inputs.node_version_file }}

    - name: Install dependencies
      run: |
        set -ex
        [ -f ${{ inputs.env_file }} ] && source ${{ inputs.env_file }}
        ${{ inputs.build_command }}
      working-directory: ${{ inputs.build_path }}

    - name: Build application
      run: |
        set -ex
        ${{ inputs.package_manager }} run build;
      working-directory: ${{ inputs.build_path }}

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: ${{ vars.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
        project_id: ${{ vars.CLOUDSDK_CORE_PROJECT }}

    - id: 'upload-folder'
      uses: 'google-github-actions/upload-cloud-storage@v2'
      with:
        path: ${{ format('{0}/{1}',inputs.build_path,inputs.upload_folder) }}
        destination: ${{ inputs.bucket }}
        parent: false
