---
name: Go upload to S3

on:
  workflow_call:
    inputs:
      artifact:
        description: "Artifact file name"
        type: string
        required: false
        default: "${{ github.event.repository.name }}.linux.amd64"
      aws_bucket:
        description: "AWS bucket"
        type: string
        required: false
        default: "remerge-artifacts-v2"
      directory:
        description: "Directory in AWS bucket"
        type: string
        required: false
        default: "${{ github.repository }}/${{ github.head_ref || github.ref_name }}"
      os:
        description: "OS version to run the workflow on. If not provided, defaults to 'ubuntu-latest'"
        type: string
        default: ubuntu-latest
        required: false
    secrets:
      aws_key_id:
        description: "AWS Key ID"
        required: true
      aws_key_secret:
        description: "AWS Key Secret"
        required: true

jobs:
  go-upload-s3:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact }}
      - run: chmod +x ${{ inputs.artifact }}
      - run: tar -czvf ${{ inputs.artifact }}.tar.gz ${{ inputs.artifact }}
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl private --follow-symlinks --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_key_secret}}
          AWS_S3_BUCKET: ${{ inputs.aws_bucket }}
          SOURCE_DIR: "./"
          DEST_DIR: ${{ inputs.directory }}
